version: 0.2

env:
  variables:
    CLOUD9_OWNER_ARN: CLOUD9_OWNER_ARN
    CFN_RESPONSE_URL: CFN_RESPONSE_URL_NOT_SET
    CFN_STACK_ID: CFN_STACK_ID_NOT_SET
    CFN_REQUEST_ID: CFN_REQUEST_ID_NOT_SET
    CFN_LOGICAL_RESOURCE_ID: CFN_LOGICAL_RESOURCE_ID_NOT_SET

phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: 14
    commands:
      - cd $CODEBUILD_SRC_DIR
      - npm install
  pre_build:
    on-failure: ABORT
    commands:
      - cd $CODEBUILD_SRC_DIR
      - npm run build
      - 'export AWS_ACCOUNT_ID=$(echo $CODEBUILD_BUILD_ARN | cut -d: -f5)'
      - 'echo "AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID"'
      - npx cdk bootstrap aws://$AWS_ACCOUNT_ID/$AWS_REGION
  build:
    on-failure: ABORT
    commands:
      - cd $CODEBUILD_SRC_DIR
      - 'export AWS_ACCOUNT_ID=$(echo $CODEBUILD_BUILD_ARN | cut -d: -f5)'
      - 'echo "AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID"'
      - 'echo "CLOUD9_OWNER_ARN: $CLOUD9_OWNER_ARN"'
      - npx cdk destroy Cloud9CustomizationCdkStack --force